language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1.7
env:
  global:
    - MIX_ENV=test
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
script:
  # Run all tests except pending ones
  - mix clean || travis_terminate 1
  - mix compile || travis_terminate 1
  - mix test || travis_terminate 1
