sudo: false

language: elixir

elixir:
  - 1.6.3
otp_release:
  - 20.2
env:
  global:
    - MIX_ENV=test
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
script:
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/priv:$LD_LIBRARY_PATH
  - export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
  - sudo ln -sv $TRAVIS_BUILD_DIR/priv/libUACryptoQ.so /usr/local/lib/libUACryptoQ.so.1 || travis_terminate 1
  - mix compile || travis_terminate 1
  - ldd $TRAVIS_BUILD_DIR/priv/digital_signature_lib_nif.so
  - mix test --exclude pending --trace || travis_terminate 1
