language: elixir

elixir:
  - 1.6.4
otp_release:
  - 20.3
env:
  global:
    - MIX_ENV=test
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
script:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - export LIBRARY_PATH=$LD_LIBRARY_PATH
  - sudo ln -sv $TRAVIS_BUILD_DIR/priv/libUACryptoQ.so /usr/local/lib/libUACryptoQ.so.1 || travis_terminate 1
  - mix compile || travis_terminate 1
  - ldd $TRAVIS_BUILD_DIR/priv/digital_signature_lib_nif.so
  - mix test --exclude pending --trace || travis_terminate 1
