sudo: false

language: elixir

elixir:
  - 1.6.3
otp_release:
  - 20.3
env:
  global:
    - MIX_ENV=test
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
script:
  - mix compile || travis_terminate 1
  - sudo ln -s $TRAVIS_BUILD_DIR/priv/libUACryptoQ.so /usr/lib/libUACryptoQ.so.1
  - mix test --exclude pending --trace || travis_terminate 1
