language: elixir
cache:
  directories:
    - deps
elixir:
  - 1.5.2
otp_release:
  - 20.1.7
env:
  global:
    - MIX_ENV=test
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clang
cript:
  # Run all tests except pending ones
  - ./bin/mix_tests.sh || travis_terminate 1
