language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1.7
env:
  global:
    - MIX_ENV=test
    - CC=gcc
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
addons:
  apt:
    packages:
      - autoconf
      - make
      - gcc
      - make
      - ragel
      - gnupg
      - openssl
script:
  - mix compile || travis_terminate 1
  - mix test || travis_terminate 1
