language: bash

sudo: true

services:
  - docker

branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/

before_script:
  - IMAGE=$(docker build -f Dockerfile.test . | tail -1 | awk '{ print $NF }')
  - CONTAINER=$(docker run -d $IMAGE /bin/bash -c 'cd /home/digital_signature.lib; mix test --exclude pending --trace')

script:
  - sudo docker attach $CONTAINER
  - sudo docker wait $CONTAINER || travis_terminate 1

after_script:
  - sudo docker rm $CONTAINER
