language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1.7
env:
  global:
    - MIX_ENV=test
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc autoconf ragel make gnupg locales openssl libssl-dev
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
script:
  # Run all tests except pending ones
  - mix compile || travis_terminate 1
  - mix test || travis_terminate 1
