sudo: false

language: elixir

elixir:
  - 1.5.2
otp_release:
  - 20.1.7
env:
  global:
    - MIX_ENV=test
addons:
  apt:
    packages:
    - gcc
    - make
    - gnupg
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
script:
  - mix compile || travis_terminate 1
  - mix test --exclude pending --trace || travis_terminate 1
