FROM elixir:1.6

ADD . /home/digital_signature.lib
WORKDIR /home/digital_signature.lib

ENV MIX_ENV=test

RUN mix do \
      local.hex --force, \
      local.rebar --force, \
      deps.get, \
      deps.compile
