FROM debian:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    gcc \
    make \
    wget \
    gnupg \
    locales

# Set UTF-8 locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8

# Install Erlang & Elixir
RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && \
    DEBIAN_FRONTEND=noninteractive dpkg -i erlang-solutions_1.0_all.deb

RUN apt-get update && apt-get -y install \
    esl-erlang \
    elixir

ADD . /home/digital_signature.lib
WORKDIR /home/digital_signature.lib

ENV MIX_ENV=test

CMD mix do \
      local.hex --force, \
      local.rebar --force, \
      deps.get, \
      test /home/digital_signature.lib/test/digital_signature_test.exs:47
